import type { Metadata } from "next";
import { GeistSans } from "geist/font";
import "./globals.css";
import Navbar from "@/components/navbar";
import ConvexProvider from "@/components/providers/convex-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <ConvexProvider>
          <Navbar />
          {children}
        </ConvexProvider>
      </body>
    </html>
  );
}
